server:
  port: 7073 # 端口
spring:
  application:
    name : server-provider # 应用名称
# 配置 Eureka Server 注册中心
eureka:
  instance :
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  ##主机名，不配置的时俄将根据操作系统的主机名来获取
  client:
    read-timeout-ms: 3000
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server02:8762/eureka/,http://eureka-server03:8763/eureka/

# 度里指标监控与健康检查
management :
  endpoints:
    web :
      exposure:
        include: shutdown # 开启 shutdown 端点访问
  endpoint :
    shutdown :
      enabled: true  # 开启 shutdown 实现优雅停服