server:
  port: 7071 # 端口
spring:
  application:
    name : server-consumer # 应用名称
# 配置 Eureka Server 注册中心
eureka:
  server:
    enable-self-preservation: false # true: 开启自我保护模式，false: 关团自我保护模式
    eviction-interval-timer-in-ms: 60000 # 清理间隔(单位: 套秒，默认是 68*1000)
    eureka-server-read-timeout-seconds: 3
  instance :
#    lease-renewal-interval-in-seconds: 3  # 心跳间隔
#    lease-expiration-duration-in-seconds: 9  # 失效阈值
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  ##主机名，不配置的时俄将根据操作系统的主机名来获取
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server02:8762/eureka/,http://eureka-server03:8763/eureka/

# 度里指标监控与健康检查
management :
  endpoints:
    web :
      exposure:
        include: shutdown # 开启 shutdown 端点访问
  endpoint :
    shutdown :
      enabled: true  # 开启 shutdown 实现优雅停服

ribbon:
  ConnectTimeout: 3000

feign:
  hystrix:
    enabled: true
